!StandardConfig
experiment: !ExperimentConfig
  name: "MOSI_Text_Encoder_Pretrain"
  device: "cuda"
  train_print_interval_epochs: 1
  validation_print_interval_epochs: 1
  is_train: true
  is_test: true

model: !ModelConfig
  name: "MOSI_Text_Encoder"
  model_type: "UttFusionModel"

  # Только энкодер текста
  netT: !TextCNN
    input_size: 768
    embd_size: 64
    dropout: 0.5
    in_channels: 1
    out_channels: 128
    kernel_heights: 
      - 3
      - 4
      - 5

training:
  epochs: 100
  early_stopping: true
  early_stopping_patience: 10
  num_modalities: 1
  optimizer: !Optimizer
    name: "Adam"
    default_kwargs:
      lr: 1e-3
      weight_decay: 0.001
  loss_functions: !LossFunctionGroup
    cross_entropy: 
      loss_name: "cross_entropy"
      loss_args: {}
      weight: 1.0

data: !DataConfig
  datasets:
    train: !DatasetConfig
      dataset: "MOSI"
      data_fp: "$EXP_PATH/DATA/mosi/aligned_50.pkl"
      split: "train"
      target_modality: !Modality "TEXT"
      batch_size: 32
      shuffle: true
      missing_patterns: !MissingPatternConfig
        modalities:
          !Modality TEXT: !ModalityConfig
            missing_rate: 0.0
        selected_patterns: ["t"]
      kwargs:
        labels_key: "classification_labels"
        aligned: true
    validation: !DatasetConfig
      dataset: "MOSI"
      data_fp: "$EXP_PATH/DATA/mosi/aligned_50.pkl"
      split: "valid"
      target_modality: !Modality "TEXT"
      shuffle: true
      batch_size: 32
      missing_patterns: !MissingPatternConfig
        modalities:
          !Modality TEXT: !ModalityConfig
            missing_rate: 0.0
        selected_patterns: ["t"]
      kwargs:
        aligned: true
        labels_key: "classification_labels"
    test: !DatasetConfig
      dataset: "MOSI"
      data_fp: "$EXP_PATH/DATA/mosi/aligned_50.pkl"
      split: "test"
      target_modality: !Modality "TEXT"
      shuffle: true
      batch_size: 32
      missing_patterns: !MissingPatternConfig
        modalities:
          !Modality TEXT: !ModalityConfig
            missing_rate: 0.0
        selected_patterns: ["t"]
      kwargs:
        aligned: true
        labels_key: "classification_labels"

metrics:
  metrics:
    MSA:
      function: "metrics.msa_binary_classification"
      kwargs: {}
      level: "epoch"
    ConfusionMatrix:
      function: "sklearn.metrics.confusion_matrix"
      kwargs: 
        labels: [0, 1, 2]
      level: "epoch"
  groups:
    classification: ["MSA", "ConfusionMatrix"]

logging:
  log_path: "$EXP_PATH/experiments_output/{experiment_name}/logs/{run_id}"
  model_output_path: "$EXP_PATH/experiments_output/{experiment_name}/models/{run_id}"
  metrics_path: "$EXP_PATH/experiments_output/{experiment_name}/metrics/{run_id}"
  save_metric: "loss"
  monitor_path: "$EXP_PATH/experiments_output/{experiment_name}/monitoring/{run_id}"
  tensorboard_path: "$EXP_PATH/experiments_output/{experiment_name}/tensorboard/{run_id}"
  tb_record_only:
    - "loss"

monitoring:
  enabled: false