!StandardConfig
experiment: !ExperimentConfig
  name: "Self-MM MOSI Multimodal Training"
  device: "cuda"
  train_print_interval_epochs: 4
  validation_print_interval_epochs: 4
  is_train: true
  is_test: true

model: !ModelConfig
  name: "SELF-MM"
  model_type: "Self-MM"
  
  # Individual encoders
  text_encoder: !BertTextEncoder
    language: "en"
    use_finetune: true
    pretrained_path: "$EXP_PATH/DATA/pretrained_berts/bert_en"
    
  audio_encoder: !AuViSubNet
    in_size: 5
    hidden_size: 32
    out_size: 16
    num_layers: 1
    dropout: 0.0


  video_encoder: !AuViSubNet
    in_size: 20
    hidden_size: 64
    out_size: 32
    num_layers: 1
    dropout: 0.0

  audio_out: 16
  video_out: 32
  text_out: 768

  post_fusion_dim: 128
  post_audio_dim: 16
  post_video_dim: 32
  post_text_dim: 64

  post_fusion_dropout: 0.1
  post_audio_dropout: 0.1
  post_video_dropout: 0.1
  post_text_dropout: 0.0
  
  update_every: 4
  need_data_aligned: False


  # Feature management
  feature_manager: !FeatureManager
    modality_dims: 
      !Modality multimodal: 128
      !Modality text: 64
      !Modality audio: 16
      !Modality video: 32
    device: "cuda"
  
  center_manager: !CenterManager
    modality_dims:
      !Modality multimodal: 128
      !Modality text: 64
      !Modality audio: 16
      !Modality video: 32
    device: "cuda"
    exclude_zero: true
    
  labels_manager: !LabelManager
    modalities: 
      - !Modality multimodal
      - !Modality text
      - !Modality audio
      - !Modality video
    device: "cuda"

training:
  epochs: 50
  batch_size: 32 
  early_stopping: false ## Early stopping is bit difficult with this model since it get's updated every 4 epochs, whereas the early stopper still checks every epoch !TODO: Fix this
  num_modalities: 3
  
  # Optimizer settings with modality-specific parameters
  optimizer: !Optimizer
    name: "Adam"
    param_groups:
      - name: "text_params"
        pattern: ["text"]  
        lr: 5e-5
        weight_decay: 0.001

      - name: "audio"
        pattern: ["audio"]  
        lr: 1e-3
        weight_decay: 0.01

      - name: "video_params"
        pattern: ["video"]  
        lr: 1e-4
        weight_decay: 0.001

    # Default settings for parameters not covered by the above groups
    default_kwargs:
      lr: 1e-3
      weight_decay: 0.001
    
  scheduler: "plateau"
  scheduler_kwargs:
    mode: "min"
    factor: 0.5
    patience: 5
    min_lr: 0.00001
  
  criterion: "na"  # Implemented in the model
  update_epochs: 1  # How often to update labels

data: !DataConfig
  datasets:
    train: !DatasetConfig
      dataset: "MOSI"
      data_fp: "$EXP_PATH/DATA/MOSI/aligned_50.pkl"
      split: "train"
      target_modality: !Modality "MULTIMODAL"
      shuffle: true
      missing_patterns: !MissingPatternConfig
        modalities:
          audio: !ModalityConfig
            missing_rate: 0.0  # Audio is ALWAYS present when included in pattern
          video: !ModalityConfig
            missing_rate: 0.0  # Video is ALWAYS present when included in pattern
          text: !ModalityConfig 
            missing_rate: 0.0  # Text is ALWAYS present when included in pattern
        selected_patterns: ["avt"]  # Only use these combinations of modalities
      kwargs:
        aligned: true
    validation: !DatasetConfig
      dataset: "MOSI"
      data_fp: "$EXP_PATH/DATA/MOSI/aligned_50.pkl"
      split: "valid"
      shuffle: true
      target_modality: !Modality "MULTIMODAL"
      missing_patterns: !MissingPatternConfig
        modalities:
          audio: !ModalityConfig
            missing_rate: 0.0  # Audio is ALWAYS present when included in pattern
          video: !ModalityConfig
            missing_rate: 0.0  # Video is ALWAYS present when included in pattern
          text: !ModalityConfig 
            missing_rate: 0.0  # Text is ALWAYS present when included in pattern
        selected_patterns: ["avt", "a", "v", "t", "av", "at", "vt"]
      kwargs:
        aligned: true

    test: !DatasetConfig
      dataset: "MOSI"
      data_fp: "$EXP_PATH/DATA/MOSI/aligned_50.pkl"
      split: "test"
      target_modality: !Modality "MULTIMODAL"
      shuffle: true
      missing_patterns: !MissingPatternConfig
        modalities:
          audio: !ModalityConfig
            missing_rate: 0.0  # Audio is ALWAYS present when included in pattern
          video: !ModalityConfig
            missing_rate: 0.0  # Video is ALWAYS present when included in pattern
          text: !ModalityConfig 
            missing_rate: 0.0  # Text is ALWAYS present when included in pattern
        selected_patterns: ["avt", "a", "v", "t", "av", "at", "vt"]
      kwargs:
        aligned: true
    embeddings: !DatasetConfig
      dataset: "MOSI"
      data_fp: "$EXP_PATH/DATA/MOSI/aligned_50.pkl"
      split: "test"
      target_modality: !Modality "MULTIMODAL"
      shuffle: true
      missing_patterns: !MissingPatternConfig
        modalities:
          audio: !ModalityConfig
            missing_rate: 0.0  # Audio is ALWAYS present when included in pattern
          video: !ModalityConfig
            missing_rate: 0.0  # Video is ALWAYS present when included in pattern
          text: !ModalityConfig 
            missing_rate: 0.0  # Text is ALWAYS present when included in pattern
        selected_patterns: ["avt"]
      kwargs:
        aligned: true
metrics:
  metrics:
    MAE:
      function: "sklearn.metrics.mean_absolute_error"
      kwargs: {}
      level: "batch"  
    MSE:
      function: "sklearn.metrics.mean_squared_error"
      kwargs: {}
      level: "batch"
    MSA:
      function: "metrics.mosei_regression"
      kwargs: {}
      level: "epoch"

logging:
  log_path: "$EXP_PATH/experiments_output/{experiment_name}/logs/{run_id}"
  model_output_path: "$EXP_PATH/experiments_output/{experiment_name}/models/{run_id}"
  metrics_path: "$EXP_PATH/experiments_output/{experiment_name}/metrics/{run_id}"
  save_metric: "loss"
  monitor_path: "$EXP_PATH/experiments_output/{experiment_name}/monitoring/{run_id}"

monitoring:
  enabled: false
  gradient_interval: 100
  activation_interval: 100
  weight_interval: 200
  buffer_size: 1000
  compression: "gzip"
  compression_opts: 4
  enable_gradient_tracking: true
  enable_activation_tracking: true
  enable_weight_tracking: true
  enable_layer_convergence: true
  enable_information_flow: false