!StandardConfig
experiment: !ExperimentConfig
  name: "MMIN MOSI Multimodal Training"
  device: "cuda"
  train_print_interval_epochs: 1
  validation_print_interval_epochs: 1
  is_train: true
  is_test: true

model: !ModelConfig
  name: "Utt-Fusion"
  model_type: "UttFusionModel"
  
  netA: !LSTMEncoder
    input_size: 74
    hidden_size: 96
    embd_method: "maxpool"

  netV: !LSTMEncoder
    input_size: 34
    hidden_size: 96
    embd_method: "maxpool"

  netT: !TextCNN
    input_size: 768
    embd_size: 696

  
  netAE: !ResidualAE
    layers: [160, 80, 32]
    n_blocks: 5
    input_dim: 74
    dropout: 0.5

  netC: !FcClassifier
    input_dim: 288
    layers: [96, 96]
    output_dim: 3
    dropout: 0.5

    clip: 1.0

    pretrained_model: !UttFusionModel
      pretrained_path: ""
        netA: !LSTMEncoder
      input_size: 74
      hidden_size: 96
      embd_method: "maxpool"

      netV: !LSTMEncoder
        input_size: 34
        hidden_size: 96
        embd_method: "maxpool"

      netT: !TextCNN
        input_size: 768
        embd_size: 696
        dropout: 0.5
        in_channels: 1
        out_channels: 128
        kernel_heights: [3, 4, 5]
      
      netC: !FcClassifier
        input_dim: 288
        layers: [96, 96]
        output_dim: 3
        dropout: 0.5


  clip: 1.0
  
training:
  epochs: 50
  batch_size: 32
  early_stopping: false ## Early stopping is bit difficult with this model since it get's updated every 4 epochs, whereas the early stopper still checks every epoch !TODO: Fix this
  num_modalities: 3
  
  # Optimizer settings with modality-specific parameters
  optimizer: !Optimizer
    name: "Adam"
    # Default settings for parameters not covered by the above groups
    default_kwargs:
      lr: 2e-4
      weight_decay: 0.00001
      betas: [0.9, 0.999]
    

  criterion: !LossFunctionGroup
    "ce": 
      weight: 1.0
    "mse":
      weight: 4.0
    "cycle": 
      weight: 2.0

data: !DataConfig
  datasets:
    train: !DatasetConfig
      dataset: "MOSI"
      data_fp: "$EXP_PATH/DATA/MOSI/aligned_50.pkl"
      split: "train"
      target_modality: !Modality "MULTIMODAL"
      shuffle: true
      missing_patterns: !MissingPatternConfig
        modalities:
          audio: !ModalityConfig
            missing_rate: 0.0  # Audio is ALWAYS present when included in pattern
          video: !ModalityConfig
            missing_rate: 0.0  # Video is ALWAYS present when included in pattern
          text: !ModalityConfig 
            missing_rate: 0.0  # Text is ALWAYS present when included in pattern
        selected_patterns: ["avt"]  # Only use these combinations of modalities
      kwargs:
        aligned: true
    validation: !DatasetConfig
      dataset: "MOSI"
      data_fp: "$EXP_PATH/DATA/MOSI/aligned_50.pkl"
      split: "valid"
      shuffle: true
      target_modality: !Modality "MULTIMODAL"
      missing_patterns: !MissingPatternConfig
        modalities:
          audio: !ModalityConfig
            missing_rate: 0.0  # Audio is ALWAYS present when included in pattern
          video: !ModalityConfig
            missing_rate: 0.0  # Video is ALWAYS present when included in pattern
          text: !ModalityConfig 
            missing_rate: 0.0  # Text is ALWAYS present when included in pattern
        selected_patterns: ["avt", "a", "v", "t", "av", "at", "vt"]
      kwargs:
        aligned: true

    test: !DatasetConfig
      dataset: "MOSI"
      data_fp: "$EXP_PATH/DATA/MOSI/aligned_50.pkl"
      split: "test"
      target_modality: !Modality "MULTIMODAL"
      shuffle: true
      missing_patterns: !MissingPatternConfig
        modalities:
          audio: !ModalityConfig
            missing_rate: 0.0  # Audio is ALWAYS present when included in pattern
          video: !ModalityConfig
            missing_rate: 0.0  # Video is ALWAYS present when included in pattern
          text: !ModalityConfig 
            missing_rate: 0.0  # Text is ALWAYS present when included in pattern
        selected_patterns: ["avt", "a", "v", "t", "av", "at", "vt"]
      kwargs:
        aligned: true
    embeddings: !DatasetConfig
      dataset: "MOSI"
      data_fp: "$EXP_PATH/DATA/MOSI/aligned_50.pkl"
      split: "test"
      target_modality: !Modality "MULTIMODAL"
      shuffle: true
      missing_patterns: !MissingPatternConfig
        modalities:
          audio: !ModalityConfig
            missing_rate: 0.0  # Audio is ALWAYS present when included in pattern
          video: !ModalityConfig
            missing_rate: 0.0  # Video is ALWAYS present when included in pattern
          text: !ModalityConfig 
            missing_rate: 0.0  # Text is ALWAYS present when included in pattern
        selected_patterns: ["avt"]
      kwargs:
        aligned: true

metrics:
  metrics:
    MAE:
      function: "sklearn.metrics.mean_absolute_error"
      kwargs: {}
      level: "epoch"  
    MSE:
      function: "sklearn.metrics.mean_squared_error"
      kwargs: {}
      level: "epoch"
    MSA:
      function: "metrics.mosei_regression"
      kwargs: {}
      level: "epoch"

logging:
  log_path: "$EXP_PATH/experiments_output/{experiment_name}/logs/{run_id}"
  model_output_path: "$EXP_PATH/experiments_output/{experiment_name}/models/{run_id}"
  metrics_path: "$EXP_PATH/experiments_output/{experiment_name}/metrics/{run_id}"
  save_metric: "loss"
  monitor_path: "$EXP_PATH/experiments_output/{experiment_name}/monitoring/{run_id}"

monitoring:
  enabled: false
  gradient_interval: 100
  activation_interval: 100
  weight_interval: 200
  buffer_size: 1000
  compression: "gzip"
  compression_opts: 4
  enable_gradient_tracking: true
  enable_activation_tracking: true
  enable_weight_tracking: true
  enable_layer_convergence: true
  enable_information_flow: false