!CMAMConfig
experiment: !ExperimentConfig
  name: "UTT_FUSION MOSEI C-MAM Video Text to Audio Cosine MSE"
  device: "cuda"
  train_print_interval_epochs: 1
  validation_print_interval_epochs: 1
  is_train: true
  is_test: true

model: !ModelConfig
  name: "UTT-Fusion"
  model_type: "UttFusionModel"
  pretrained_path: "$EXP_PATH/experiments_output/UTT_FUSION_BASE_MODEL_MOSEI/models/{run_id}/best.pth"
  netA: !LSTMEncoder
    input_size: 74
    hidden_size: 64
    embd_method: "maxpool"

  netV: !LSTMEncoder
    input_size: 35
    hidden_size: 64
    embd_method: "maxpool"

  netT: !TextCNN
    input_size: 768
    embd_size: 64
    dropout: 0.7
    in_channels: 1
    out_channels: 128
    kernel_heights: 
      - 3
      - 4
      - 5
  netC: !FcClassifier
    input_dim: 192
    layers: 
      - 96
      - 48
    output_dim: 3
    dropout: 0.66
    use_bn: true

  clip: 0.5

cmam: !ModelConfig
  name: "CMAM"
  model_type: "CMAM"
  target_modality: !Modality audio
  load_pretrained_encoder_state_for: []
  labels_key: "label"
  input_encoders: !InputEncoders
    !Modality Video: !LSTMEncoder
      input_size: 35
      hidden_size: 64
      embd_method: "maxpool"
    !Modality Text: !TextCNN
      input_size: 768
      embd_size: 64
      dropout: 0.7
      in_channels: 1
      out_channels: 128
      kernel_heights: 
        - 3
        - 4
        - 5
  association_network: !AssociationNetwork
    input_size: 128
    hidden_size: 64
    output_size: 64
    dropout: 0.25
    batch_norm: True

training:
  epochs: 20
  batch_size: 256 
  early_stopping: false
  early_stopping_patience: 15
  early_stopping_metric: "loss"
  num_modalities: 3
  optimizer: !Optimizer
    name: "Adam"
    default_kwargs:
      lr: 2e-4
      weight_decay: 0.00001
  loss_functions: !LossFunctionGroup
    cmam: 
      loss_name: "cmam"
      loss_kwargs: {
        cosine_weight: 1.0,
        mse_weight: 1.0,
        mae_weight: 0.0,
        cls_weight: 0.00
      }
      weight: 1.0  

data: !DataConfig
  datasets:
    train: !DatasetConfig
      dataset: "mosei"
      data_fp: "$EXP_PATH/DATA/mosei/aligned.pkl"
      split: "train"
      target_modality: !Modality "MULTIMODAL"
      shuffle: true
      missing_patterns: !MissingPatternConfig
        modalities:
          !Modality audio: !ModalityConfig
            missing_rate: 0.0  # Audio is ALWAYS present when included in pattern
          !Modality video: !ModalityConfig
            missing_rate: 0.0  # Video is ALWAYS present when included in pattern
          !Modality text: !ModalityConfig 
            missing_rate: 0.0  # Text is ALWAYS present when included in pattern
        selected_patterns: ["avt"]  # Only use these combinations of modalities
      kwargs:
        labels_key: "classification_labels"
        aligned: true
    validation: !DatasetConfig
      dataset: "mosei"
      data_fp: "$EXP_PATH/DATA/mosei/aligned.pkl"
      split: "valid"
      shuffle: true
      target_modality: !Modality "MULTIMODAL"
      missing_patterns: !MissingPatternConfig
        modalities:
          !Modality audio: !ModalityConfig
            missing_rate: 0.0  # Audio is ALWAYS present when included in pattern
          !Modality video: !ModalityConfig
            missing_rate: 0.0  # Video is ALWAYS present when included in pattern
          !Modality text: !ModalityConfig 
            missing_rate: 0.0  # Text is ALWAYS present when included in pattern
        selected_patterns: ["avt"]
      kwargs:
        aligned: true
        labels_key: "classification_labels"

    test: !DatasetConfig
      dataset: "mosei"
      data_fp: "$EXP_PATH/DATA/mosei/aligned.pkl"
      split: "test"
      target_modality: !Modality "MULTIMODAL"
      shuffle: true
      missing_patterns: !MissingPatternConfig
        modalities:
          !Modality audio: !ModalityConfig
            missing_rate: 0.0  # Audio is ALWAYS present when included in pattern
          !Modality video: !ModalityConfig
            missing_rate: 0.0  # Video is ALWAYS present when included in pattern
          !Modality text: !ModalityConfig 
            missing_rate: 0.0  # Text is ALWAYS present when included in pattern
        selected_patterns: ["avt"]
      kwargs:
        aligned: true
        labels_key: "classification_labels"

    embeddings: !DatasetConfig
      dataset: "mosei"
      data_fp: "$EXP_PATH/DATA/mosei/aligned.pkl"
      split: "test"
      target_modality: !Modality "MULTIMODAL"
      shuffle: true
      missing_patterns: !MissingPatternConfig
        modalities:
          !Modality audio: !ModalityConfig
            missing_rate: 0.0  # Audio is ALWAYS present when included in pattern
          !Modality video: !ModalityConfig
            missing_rate: 0.0  # Video is ALWAYS present when included in pattern
          !Modality text: !ModalityConfig 
            missing_rate: 0.0  # Text is ALWAYS present when included in pattern
        selected_patterns: ["avt"]
      kwargs:
        aligned: true
        labels_key: "classification_labels"

metrics:
  metrics:
    Accuracy:
      function: "sklearn.metrics.accuracy_score"
      kwargs: {}
      level: "epoch"
    F1_Weighted:
      function: "sklearn.metrics.f1_score"
      kwargs: 
        average: "weighted"
        zero_division: 0
      level: "epoch"    
    F1_Micro:
      function: "sklearn.metrics.f1_score"
      kwargs: 
        average: "micro"
        zero_division: 0
      level: "epoch"
    F1_Macro:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "macro"
        zero_division: 0
      level: "epoch"
    Precision_Weighted:
      function: "sklearn.metrics.precision_score"
      kwargs: 
        average: "weighted"
        zero_division: 0
      level: "epoch"
    Precision_Micro:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "micro"
        zero_division: 0
      level: "epoch"
    Precision_Macro:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "macro"
        zero_division: 0
      level: "epoch"
    Recall_Weighted:
      function: "sklearn.metrics.recall_score"
      kwargs: 
        average: "weighted"
        zero_division: 0
      level: "epoch"
    Recall_Micro:
      function: "sklearn.metrics.recall_score"
      kwargs: 
        average: "micro"
        zero_division: 0
      level: "epoch"
    Recall_Macro:
      function: "sklearn.metrics.recall_score"
      kwargs: 
        average: "macro"
        zero_division: 0
      level: "epoch"
    MSA:
      function: "metrics.msa_binary_classification"
      kwargs: {}
      level: "epoch"
    ConfusionMatrix:
      function: "metrics.confusion_matrix_from_logits"
      kwargs: {
        "labels": [0, 1, 2]
      }
      level: "epoch"
    mae:
      function: "sklearn.metrics.mean_absolute_error"
      kwargs: {}
    mse:
      function: "sklearn.metrics.mean_squared_error"
      kwargs: {}
    cosine:
      function: "metrics.cosine_similarity"
      kwargs: {}
  groups:
      classification: ["MSA", "F1_Weighted", "F1_Micro", "F1_Macro", "Precision_Weighted", "Precision_Micro", "Precision_Macro", "Recall_Weighted", "Recall_Micro", "Recall_Macro", "ConfusionMatrix"]
      reconstruction: ["mae", "mse", "cosine"]

logging:
  log_path: "$EXP_PATH/experiments_output/{experiment_name}/logs/{run_id}"
  model_output_path: "$EXP_PATH/experiments_output/{experiment_name}/models/{run_id}"
  metrics_path: "$EXP_PATH/experiments_output/{experiment_name}/metrics/{run_id}"
  save_metric: "loss"
  monitor_path: "$EXP_PATH/experiments_output/{experiment_name}/monitoring/{run_id}"

monitoring:
  enabled: false
  gradient_interval: 100
  activation_interval: 100
  weight_interval: 200
  buffer_size: 1000
  compression: "gzip"
  compression_opts: 4
  enable_gradient_tracking: true
  enable_activation_tracking: true
  enable_weight_tracking: true
  enable_layer_convergence: true
  enable_information_flow: false