!StandardConfig
experiment: !ExperimentConfig
  name: "MMIMDb Baseline Multimodal Training"
  device: "cuda"
  train_print_interval_epochs: 1
  validation_print_interval_epochs: 1
  is_train: true
  is_test: true

model: !ModelConfig
  name: "MMIMDb"
  model_type: "MMIMDb"

  image_encoder: !MMIMDbModalityEncoder
    input_dim: 4096
    output_dim: 512
  
  text_encoder: !MMIMDbModalityEncoder
    input_dim: 300
    output_dim: 512

  gated_bimodal_network: !GatedBiModalNetwork
    input_one_dim: 512
    output_one_dim: 512
    input_two_dim: 512
    output_two_dim: 512

  classifier: !MLPGenreClassifier
    input_dim: 512
    hidden_dim: 512
    output_dim: 23

training:
  epochs: 50
  early_stopping: true
  early_stopping_patience: 15
  num_modalities: 2
  optimizer: !Optimizer
    name: "Adam"
    default_kwargs:
      lr: 0.00001
      weight_decay: 0.001
  criterion: "bce_with_logits"

data: !DataConfig
  datasets:
    train: !DatasetConfig
      dataset: "MMIMDb"
      data_fp: "$EXP_PATH/DATA/mmimdb/train.hdf5"
      split: "train"
      target_modality: !Modality "MULTIMODAL"
      batch_size: 128
      shuffle: true
      missing_patterns: !MissingPatternConfig
        modalities:
          text: !ModalityConfig
            missing_rate: 0.0
          image: !ModalityConfig
            missing_rate: 0.0
        selected_patterns: ["it"]
    validation: !DatasetConfig
      dataset: "AVMNIST"
      data_fp: "$EXP_PATH/DATA/mmimdb/validation.hdf5"
      split: "valid"
      target_modality: !Modality "MULTIMODAL"
      shuffle: true
      batch_size: 128
      missing_patterns: !MissingPatternConfig
        modalities:
          text: !ModalityConfig
            missing_rate: 0.0
          image: !ModalityConfig
            missing_rate: 0.0
        selected_patterns: ["it", "i", "t"]
    test: !DatasetConfig
      dataset: "AVMNIST"
      data_fp: "$EXP_PATH/DATA/mmimdb/test.hdf5"
      split: "test"
      target_modality: !Modality "MULTIMODAL"
      shuffle: true
      batch_size: 128
      missing_patterns: !MissingPatternConfig
        modalities:
          text: !ModalityConfig
            missing_rate: 0.0
          image: !ModalityConfig
            missing_rate: 0.0
        selected_patterns: ["it", "i", "t"]

metrics:
  metrics:
    f1_samples:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "samples"
        zero_division: 0
    f1_macro:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "macro"
        zero_division: 0
    f1_weighted:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "weighted"
        zero_division: 0
    f1_micro:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "micro"
        zero_division: 0      

logging:
  log_path: "$EXP_PATH/experiments_output/{experiment_name}/logs/{run_id}"
  model_output_path: "$EXP_PATH/experiments_output/{experiment_name}/models/{run_id}"
  metrics_path: "$EXP_PATH/experiments_output/{experiment_name}/metrics/{run_id}"
  save_metric: "loss"
  monitor_path: "$EXP_PATH/experiments_output/{experiment_name}/monitoring/{run_id}"
  tensorboard_path: "$EXP_PATH/experiments_output/{experiment_name}/tensorboard/{run_id}"
  tb_only_record:
    - "loss"

monitoring:
  enabled: false
  gradient_interval: 100
  activation_interval: 100
  weight_interval: 200
  buffer_size: 1000
  compression: "gzip"
  compression_opts: 4
  enable_gradient_tracking: true
  enable_activation_tracking: true
  enable_weight_tracking: true
  enable_layer_convergence: true
  enable_information_flow: false